version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kilil-postgres
    environment:
      POSTGRES_DB: et_univ
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kilil-network

  redis:
    image: redis:7
    container_name: kilil-redis
    ports:
      - '6381:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kilil-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/realms/et-univ/.well-known/openid-configuration"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - kilil-network

volumes:
  postgres_data:
  redis_data:

networks:
  kilil-network:
    driver: bridge